### ISSUE TITLE
 OneFlow-Pruning/tests/ 中的测试用例进行了正确性测试

### ISSUE THREAD

**Issue by ccssu** [Oneflow-Inc/OneFlow-Pruning#5]
> 一个记录问题的issues: 只是简单的将 test/xx.py 中 xx.py 通过 import oneflow as torch方式测试，后续将修复发现的error
## 引言
为了验证 OneFlow-Pruning 的剪枝，，对 OneFlow-Pruning/tests/ 中的测试用例进行了正确性测试。
![image](https://user-images.githubusercontent.com/109639975/230857249-a5b5407c-f838-4834-ac7e-37517a635ec5.png)
## 测试结果
测试结果如下，目前仍然存在少量问题。
[oneflow](https://github.com/Oneflow-Inc/OneFlow-Pruning/tree/develop/oneflow_tests)

- [x] ├── test_customized_layer.py [accept]
- [x] ├── test_dependency_graph.py [accept]
- [ ] ├── test_dependency_lenet.py [error]
- [x] ├── test_fully_connected_layers.py [accept]
- [ ] ├── test_graph_drawing.py [accept]
- [ ] ├── test_importance.py[accept]
- [ ] ├── test_interactive_pruner.py[accept]
- [x] ├── test_multiple_inputs_and_outputs.py [error]
- [ ] ├── test_pruner.py[accept]
- [ ] ├── test_pruning_fn.py[accept]
- [ ] ├── test_reshape.py  [error]
- [ ] └── test_unwrapped_parameters.py  [error]

测试环境：
- 机器 a100
- pip 安装 【Oneflow包】 ：oneflow.__version__== 0.9.1.dev20230409+cu117
- 测试代码 本项目 develop 分支

<details close>
<summary> [error]s </summary>

### /test_dependency_lenet.py [error]
(oneflow-dev-clang10-v2) python test_dependency_lenet.py 
F20230410 08:04:41.052480 47541 shape.cpp:30] Check failed: index < tp()->NumAxes() (3 vs. 3)  Shape: (6,24,24) visit index: 3 > num_axes: 3
*** Check failure stack trace: ***
    @     0x7f65e46ebada  google::LogMessage::Fail()
    @     0x7f65e46eea11  google::LogMessage::SendToLog()
    @     0x7f65e46eb609  google::LogMessage::Flush()
    @     0x7f65e46ef2f9  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f65d7fdc51c  oneflow::ConstShapeMixIn<>::At()
    @     0x7f65df27c44b  oneflow::MaxPoolParams3D::MaxPoolParams3D()
    @     0x7f65e0510203  _ZZN7oneflow12_GLOBAL__N_135MaxPoolMakeForwardTensorDescInferFnEiENKUlPNS_7user_op12InferContextEE_clES3_
    @     0x7f65e0511050  oneflow::MaxPool2DOp::InferLogicalTensorDesc()
    @     0x7f65e051108a  oneflow::MaxPool2DOp::InferPhysicalTensorDesc()
    @     0x7f66b77d280e  std::_Function_handler<>::_M_invoke()
    @     0x7f65dc358841  oneflow::one::UserOpExpr::InferPhysicalTensorDesc()
    @     0x7f65dc2ebe52  oneflow::one::LocalTensorInferCache::Infer()
    @     0x7f65dc2ed76f  oneflow::one::LocalTensorInferCache::GetOrInfer()
    @     0x7f65dc38196e  _ZZN7oneflow3one14NaiveInterpretERKNS0_10UserOpExprERKNS0_11TensorTupleEPS4_RKNS0_19OpExprInterpContextEENKUlvE1_clEv
    @     0x7f65dc38c390  oneflow::one::NaiveInterpret()
    @     0x7f65dc390676  oneflow::one::EagerLocalInterpreter::ApplyImpl()
    @     0x7f65dc3d0f08  oneflow::one::EagerInterpreter::Apply()
    @     0x7f65dc3cfc40  oneflow::one::AutogradInterpreter::Apply()
    @     0x7f65dc3d7a3a  oneflow::one::OpInterpUtil::Dispatch()
    @     0x7f65dc3d805c  oneflow::one::OpInterpUtil::Dispatch<>()
    @     0x7f65dc5cd58f  oneflow::one::OpInterpUtil::Dispatch<>()
    @     0x7f65dca18a09  oneflow::one::functional::impl::MaxPoolNDFunctor::operator()()
    @     0x7f65dca19c8d  _ZNSt17_Function_handlerIFN7oneflow5MaybeINS0_3one11TensorTupleEvEERKSt10shared_ptrINS2_6TensorEERKSt6vectorIiSaIiEERKNS0_8OptionalISC_EESE_SE_RKbSK_RKSsEZNS2_10functional18PackedFunctorMakerISN_E4makeINSO_4impl16MaxPool2DFunctorELi0EEENSO_13PackedFunctorISN_EESM_RKT_EUlS9_SE_SI_SE_SE_SK_SK_SM_E_E9_M_invokeERKSt9_Any_dataS9_SE_SI_SE_SE_SK_SK_SM_
    @     0x7f65e08aee11  oneflow::one::functional::MaxPool2D()
    @     0x7f66b78af7b2  oneflow::one::functional::max_pool2d()
    @     0x560142b338ee  cfunction_call_varargs
    @     0x560142b2875f  _PyObject_MakeTpCall
    @     0x560142bd200a  _PyEval_EvalFrameDefault
    @     0x560142bc4667  _PyFunction_Vectorcall
    @     0x560142b5d9d8  method_vectorcall
    @     0x560142b2e87d  PyObject_Call
    @     0x560142bceabe  _PyEval_EvalFrameDefault
Aborted (core dumped)

### test_multiple_inputs_and_outputs.py [error]
--------------------------------

The pruned model: 
 FullyConnectedNet(
  (fc1): Linear(in_features=128, out_features=29, bias=True)
  (fc2): Linear(in_features=64, out_features=29, bias=True)
  (fc3): Linear(in_features=61, out_features=1000, bias=True)
)
Output:
Traceback (most recent call last):
  File "test_multiple_inputs_and_outputs.py", line 45, in <module>
    for o in model(torch.randn(1, 128), torch.randn(1, 64)):
  File "/home/fengwen/miniconda3/envs/oneflow-dev-clang10-v2/lib/python3.8/site-packages/oneflow/nn/modules/module.py", line 218, in __call__
    res = self.forward(*args, **kwargs)
  File "test_multiple_inputs_and_outputs.py", line 24, in forward
    x3 = F.relu(self.fc3(torch.cat([x1, x2], dim=1)))
  File "/home/fengwen/miniconda3/envs/oneflow-dev-clang10-v2/lib/python3.8/site-packages/oneflow/nn/modules/module.py", line 218, in __call__
    res = self.forward(*args, **kwargs)
  File "/home/fengwen/miniconda3/envs/oneflow-dev-clang10-v2/lib/python3.8/site-packages/oneflow/nn/modules/linear.py", line 133, in forward
    res = flow._C.matmul(x, self.weight, transpose_a=False, transpose_b=True)
RuntimeError: Check failed: (58 == 61) 
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/functional/impl/nn_functor.cpp", line 357, in operator()
    OpInterpUtil::Dispatch<Tensor>(*matmul_op_, {cast_a, cast_b}, attrs)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/framework/op_interpreter/op_interpreter_util.cpp", line 144, in Dispatch<oneflow::one::Tensor>
    Dispatch<TensorTuple>(op_expr, inputs, ctx)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/framework/op_interpreter/op_interpreter_util.cpp", line 135, in Dispatch<oneflow::one::TensorTuple>
    Dispatch(op_expr, inputs, outputs.get(), ctx)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/framework/op_interpreter/op_interpreter.cpp", line 103, in Apply
    internal_->Apply(op_expr, inputs, outputs, ctx)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/framework/op_interpreter/eager_local_op_interpreter.cpp", line 83, in NaiveInterpret
    [&]() -> Maybe<const LocalTensorInferResult> { LocalTensorMetaInferArgs ... mut_local_tensor_infer_cache()->GetOrInfer(infer_args)); }()
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/framework/op_interpreter/eager_local_op_interpreter.cpp", line 86, in operator()
    user_op_expr.mut_local_tensor_infer_cache()->GetOrInfer(infer_args)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/framework/local_tensor_infer_cache.cpp", line 209, in GetOrInfer
    Infer(*user_op_expr, infer_args)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/framework/local_tensor_infer_cache.cpp", line 178, in Infer
    user_op_expr.InferPhysicalTensorDesc( infer_args.attrs ... ) -> TensorMeta* { return &output_mut_metas.at(i); })
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/framework/op_expr.cpp", line 580, in InferPhysicalTensorDesc
    physical_tensor_desc_infer_fn_(&infer_ctx)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/user/ops/matmul_op.cpp", line 54, in InferTensorDesc4Matmul
    CHECK_EQ_OR_RETURN(k, b.shape().At(num_axes - 1))
Error Type: oneflow.ErrorProto.check_failed_error 

### (oneflow-dev-clang10-v2) python test_reshape.py 
/home/fengwen/OneFlow-Pruning/oneflow_pruning/dependency.py:298: UserWarning: Unwrapped parameters detected: ['conv1T1.weight', 'conv1T2.weight', 'conv1T1.bias', 'conv1T2.bias'].

 DepGraph requires an unwrapped_parameter list to determine the pruning_dim of nn.Parameters. By default, the last dim of a parameter matrix will be pruned.
  warnings.warn("Unwrapped parameters detected: {}.\n\n DepGraph requires an unwrapped_parameter list to determine the pruning_dim of nn.Parameters. By default, the last dim of a parameter matrix will be pruned.".format([param_to_name[p] for p in unwrapped_detected]))
Traceback (most recent call last):
  File "/home/fengwen/OneFlow-Pruning/oneflow_pruning/dependency.py", line 605, in _trace
    out = model(*example_inputs)
  File "/home/fengwen/miniconda3/envs/oneflow-dev-clang10-v2/lib/python3.8/site-packages/oneflow/nn/modules/module.py", line 218, in __call__
    res = self.forward(*args, **kwargs)
  File "test_reshape.py", line 18, in forward
    x = F.relu(self.Linear(x))
  File "/home/fengwen/miniconda3/envs/oneflow-dev-clang10-v2/lib/python3.8/site-packages/oneflow/nn/modules/module.py", line 218, in __call__
    res = self.forward(*args, **kwargs)
  File "/home/fengwen/miniconda3/envs/oneflow-dev-clang10-v2/lib/python3.8/site-packages/oneflow/nn/modules/linear.py", line 133, in forward
    res = flow._C.matmul(x, self.weight, transpose_a=False, transpose_b=True)
RuntimeError: Error: size mismatch, got 1, 512 x 4096, 512

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_reshape.py", line 32, in <module>
    pruner = tp.pruner.MagnitudePruner(
  File "/home/fengwen/OneFlow-Pruning/oneflow_pruning/pruner/algorithms/metapruner.py", line 73, in __init__
    self.DG = dependency.DependencyGraph().build_dependency(
  File "/home/fengwen/OneFlow-Pruning/oneflow_pruning/dependency.py", line 317, in build_dependency
    self.module2node = self._trace(
  File "/home/fengwen/OneFlow-Pruning/oneflow_pruning/dependency.py", line 607, in _trace
    out = model(example_inputs)
  File "/home/fengwen/miniconda3/envs/oneflow-dev-clang10-v2/lib/python3.8/site-packages/oneflow/nn/modules/module.py", line 218, in __call__
    res = self.forward(*args, **kwargs)
  File "test_reshape.py", line 19, in forward
    x = x.view(-1,self.conv1T1.in_channels, 4, 4)
  File "/home/fengwen/miniconda3/envs/oneflow-dev-clang10-v2/lib/python3.8/site-packages/oneflow/nn/modules/module.py", line 426, in __getattr__
    raise AttributeError(
AttributeError: 'ConvTranspose2d' object has no attribute 'in_channels'
Segmentation fault (core dumped)

### python test_unwrapped_parameters.py 
Traceback (most recent call last):
  File "test_unwrapped_parameters.py", line 6, in <module>
    from flowvision.models import convnext_base as entry
ImportError: cannot import name 'convnext_base' from 'flowvision.models' (/home/fengwen/miniconda3/envs/oneflow-dev-clang10-v2/lib/python3.8/site-packages/flowvision/models/__init__.py)

</deails>

**Comment by ccssu** [comment]
## 仓库启动指南

## 环境准备


### 下载代码

```
git clone git@github.com:Oneflow-Inc/OneFlow-Pruning.git
```

### 安装依赖

```shell
# https://github.com/Oneflow-Inc/oneflow#install-with-pip-package
python3 -m pip install --pre oneflow -f https://staging.oneflow.info/branch/master/cu117 # oneflow包

git checkout develop

pip install -r requirements.txt
```

### tutorials

https://github.com/Oneflow-Inc/OneFlow-Pruning/tree/develop/oneflow_tutorials

![image](https://user-images.githubusercontent.com/109639975/230880879-913b94b4-90da-4d96-87c0-0781834ecb6d.png)

**Comment by ccssu** [comment]
## 剪枝错误

```python
import sys, os

sys.path.append(os.path.dirname(os.path.dirname(os.path.realpath(__file__))))

import oneflow as torch
import oneflow.nn as nn
import oneflow.nn.functional as F

import oneflow_pruning as tp

class FullyConnectedNet(nn.Module):
    """https://github.com/VainF/Torch-Pruning/issues/21"""
    def __init__(self, input_sizes, output_sizes):
        super().__init__()
        self.fc1 = nn.Linear(input_sizes[0], output_sizes[0])
        self.fc2 = nn.Linear(input_sizes[1], output_sizes[1])
    def forward(self, x1, x2):
        x1 = self.fc1(x1)
        x1 = F.relu(x1)
        x2 = self.fc2(x2)
        print(f'{x2.shape=}')
        assert x2.shape == (1, 32)
        x2 = F.relu(x2)
        y1 = torch.cat([x1, x2], dim=1)
        return x1, x2, y1

model = FullyConnectedNet([128, 64], [32, 32])
print(f'start = {model}')

# Build dependency graph
DG = tp.DependencyGraph()
DG.build_dependency(model, example_inputs={'x1': torch.randn(1, 128), 'x2': torch.randn(1, 64)})

# get a pruning group according to the dependency graph. idxs is the indices of pruned filters.
pruning_group = DG.get_pruning_group(
    model.fc1, tp.prune_linear_out_channels, idxs=[0, 2, 4]
)
print(pruning_group)

# execute this group (prune the model)
pruning_group.prune()

print("The pruned model: \n", model)
print("Output:")
for o in model(torch.randn(1, 128), torch.randn(1, 64)):
    print('\t', o.shape)
```
下图中画框处，表示剪枝错误，fc2：不应该被剪枝的，但是被减掉了三层，说明剪枝不正确。
![image](https://user-images.githubusercontent.com/109639975/231199995-09574bb3-adc2-4fd9-85c4-c942c8cbc496.png)
